//   ^ N
// W + E
//   S
let CENTER = -1.0;
let NORTH = 0.0;
let NORTH_EAST = 1.0;
let EAST = 2.0;
let SOUTH_EAST = 3.0;
let SOUTH = 4.0;
let SOUTH_WEST = 5.0;
let WEST = 6.0;
let NORTH_WEST = 7.0;

let FOUR_DIRECTION_LIST = [NORTH, SOUTH, EAST, WEST];
let ALL_DIRECTION_LIST = [
    NORTH, NORTH_EAST,
    EAST, SOUTH_EAST,
    SOUTH, SOUTH_WEST,
    WEST, NORTH_WEST];
